//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services_DSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_NOMENCLATURE
    {
        public string CODE_STR { get; set; }
        public string CODE_NOME { get; set; }
        public string LIB_NOME { get; set; }
        public string LIB_NOME2 { get; set; }
    
        public virtual STR_NOME STR_NOME { get; set; }
    }
}
