//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services_DSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESP_INSCRIPTION
    {
        public string ANNEE_DEB { get; set; }
        public string ANNEE_FIN { get; set; }
        public string CODE_CL { get; set; }
        public string ID_ET { get; set; }
        public Nullable<decimal> COUT_ANNUEL { get; set; }
        public Nullable<decimal> FRAIS_INS { get; set; }
        public string TYPE_RGLT { get; set; }
        public string MODE_RGLT { get; set; }
        public string CODE_DEV { get; set; }
        public Nullable<decimal> COUT_DEV { get; set; }
        public string SIT_RGLT { get; set; }
        public Nullable<decimal> CREDIT_RGLT { get; set; }
        public Nullable<decimal> NB_CREDIT_MODULE { get; set; }
        public Nullable<decimal> MOY_SEM1 { get; set; }
        public Nullable<decimal> MOY_SEM2 { get; set; }
        public Nullable<decimal> MOY_GENERAL { get; set; }
        public string RESULTAT { get; set; }
        public Nullable<bool> NIVEAU_ACCEES { get; set; }
        public string TYPE_INSC { get; set; }
        public Nullable<bool> SEMESTRE { get; set; }
        public string NIV_LANGUE { get; set; }
        public string CODE_CL_LANGUE { get; set; }
        public string UTILISATEUR { get; set; }
        public string DERN_UTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATE_PREINSC { get; set; }
        public Nullable<System.DateTime> DATE_INSC { get; set; }
        public string CODE_CL1 { get; set; }
        public string CODE_CL2 { get; set; }
        public Nullable<decimal> MOY_RATT { get; set; }
        public string OBSERVATION { get; set; }
        public Nullable<short> NUMPROMOTIONCS { get; set; }
        public string CODE_DECISION_SESSION_P { get; set; }
        public string LIB_DECISION_SESSION_P { get; set; }
        public string CODE_DECISION_SESSION_RAT { get; set; }
        public string LIB_DECISION_SESSION_RAT { get; set; }
        public Nullable<byte> NB_IMP_ATTEST_REUSSITE { get; set; }
        public Nullable<System.DateTime> DATE_LAST_MAJ_DECISION_PRINC { get; set; }
        public Nullable<System.DateTime> DATE_LAST_MAJ_DECISION_RATT { get; set; }
        public string CREDIT_ANT { get; set; }
        public Nullable<byte> NB_IMP_RELEVE { get; set; }
        public string ETAT_ENTRETIEN { get; set; }
        public Nullable<System.DateTime> DATE_LAST_MODIF_RAT2 { get; set; }
        public Nullable<decimal> MOY_RAT2 { get; set; }
        public string CODE_DECISION_SESSION_RAT2 { get; set; }
        public string LIB_DECISION_SESSION_RAT2 { get; set; }
        public string ADMIS_RACH { get; set; }
        public Nullable<decimal> MOY_RAT_AV_RACH { get; set; }
        public string ADMIS_TS { get; set; }
        public Nullable<System.DateTime> DATE_LIM_PROLONG_RGLT { get; set; }
        public string NIV_ACQUIS_FRANCAIS { get; set; }
        public Nullable<bool> MAJ_NIVEAU_DEFINITIF { get; set; }
        public string RESERVE { get; set; }
        public Nullable<decimal> NB_ECTS_SP { get; set; }
        public Nullable<decimal> NB_ECTS_SR { get; set; }
        public string NIV_ACQUIS_ANGLAIS { get; set; }
        public Nullable<System.DateTime> DATE_TEST_FR { get; set; }
        public Nullable<System.DateTime> DATE_TEST_ANG { get; set; }
        public string PREP_TOEIC { get; set; }
        public string TEST_TOEIC { get; set; }
        public string ETAT_INS_TEST_NIV { get; set; }
        public string USER_LANG_MODIF { get; set; }
        public Nullable<byte> RANG_SP { get; set; }
        public Nullable<short> NUM_ANNUEL_DIPLOME { get; set; }
        public Nullable<byte> NUM_ANNEXE { get; set; }
        public string GROUPE_TARIF { get; set; }
        public Nullable<decimal> MOY_GEN_AV_PFE { get; set; }
        public Nullable<decimal> NB_ECTS_AV_PFE { get; set; }
        public Nullable<decimal> NOTE_PFE { get; set; }
        public Nullable<decimal> COEF_PFE { get; set; }
        public Nullable<decimal> MOY_GEN_AV_PFE_SP { get; set; }
        public Nullable<decimal> MOY_GEN_AV_PFE_SR { get; set; }
        public Nullable<bool> ETAT_FINANCIER { get; set; }
        public Nullable<int> TEM_NUM { get; set; }
        public Nullable<decimal> MG_SEVED { get; set; }
        public string RACHAT_UE_ET { get; set; }
        public string ENCADRANT_PEDA { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
        public Nullable<int> NUM_MOIS_INSC { get; set; }
        public Nullable<bool> NUM_SEMAINE { get; set; }
        public string NE { get; set; }
        public Nullable<System.DateTime> DATE_NE { get; set; }
        public Nullable<bool> GROUPE_RGLT { get; set; }
        public string NE2 { get; set; }
        public Nullable<decimal> SOLDE_ET { get; set; }
        public string EXPERT_PEDA { get; set; }
        public string MOTIF_RGLT { get; set; }
    
        public virtual ESP_ETUDIANT ESP_ETUDIANT { get; set; }
    }
}
