//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services_DSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICES_DSI_PRIVILEGE
    {
        public string ID { get; set; }
        public string PRIVILEGE2 { get; set; }
        public string PRIVLEGE { get; set; }
        public string FERMER { get; set; }
        public string DEPLACER { get; set; }
    }
}
